import numpy as np 

Net={
        # structure data
        "load": [("name", np.dtype(object)),
                 ('amount', 'f8'),
                 ("unit", np.dtype(object))],
        "fuzzy": [("name", np.dtype(object)),
                 ('right', 'f8'),
                 ( 'left', 'f8'),
                 ('right0', 'f8'),
                 ("left0", 'f8'),
                 ('span', 'f8'),
                 ('minup', 'f8'),
                 ('mindown', 'f8')],
        "generator": [("name", np.dtype(object)),
                 ('u_max', 'f8'),
                 ('u_min', 'f8'),
                 ('a_g', 'f8'),
                 ('b_g', 'f8'),
                 ('c_g', 'f8'),
                 ('t_up', 'f8'),
                 ('t_down', 'f8'),
                 ('hs_up', 'f8'),
                 ('cs_up', 'f8'),
                 ('t_cold', 'f8'),
                 ('t_initial', 'f8'),
                 ("unit", np.dtype(object))],
        "_empty_res_startup": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_fuzzy": [("name", np.dtype(object)),
                                ('f_gen', np.dtype(object)),
                                ('f_cost', np.dtype(object)),
                                ('f_minup', np.dtype(object)),
                                ('f_mindown', np.dtype(object)),
                                ('f_startup', np.dtype(object)),],
        "_empty_res_cost": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_on_off_schedule": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_up": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_down": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_use_schedule": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_generation": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_priority": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8')],
        "_empty_res_reward": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8'),
                                ('total_reward', 'f8'),
                                ('penalty', 'f8')],
        "_empty_res_spinnin_reserve": [("name", np.dtype(object)),
                                ('gen-0', "f8"),
                                ('gen-1', 'f8'),
                                ('gen-2', 'f8'),
                                ('gen-3', 'f8'),
                                ('gen-4', 'f8'),
                                ('gen-5', "f8"),
                                ('gen-6', 'f8'),
                                ('gen-7', 'f8'),
                                ('gen-8', 'f8'),
                                ('gen-9', 'f8'),
                                ('total gen', 'f8'),
                                ('total demand', 'f8'),
                                ('spining reserve', 'f8')],  
        "_len":24,
        "gen_len":10,
        "spining_reserve":0.01,
        "MUT":50,                         
    }